#!/usr/bin/env php
<?php
$privateKey = openssl_pkey_get_private('file://var/private_key.key');
$publicKey = openssl_pkey_get_public('file://var/ss_cert.cer');
$data = 'this is very confidential';

openssl_private_encrypt($data, $encrypted, $privateKey);
openssl_public_decrypt($encrypted, $decrypted, $publicKey);

echo "ORIGINAL_DATA:\t{$data}\nDECRYPTED_DATA:\t{$decrypted}\n";

while ($message = openssl_error_string()) {
    echo "{$message}\n";
}
